### ISSUE TITLE
[Bug] Multi Block Connect Doesn't Affect Double Seagrass

### ISSUE THREAD

**Issue by RyanCR03** [DarkKronicle/BetterBlockOutline#1]
![image](https://user-images.githubusercontent.com/32957560/147695641-79d05f1c-0a32-4e69-8780-ceb98dbd5e67.png)

**Comment by DarkKronicle** [comment]
Thanks for the bug report! Will be fixed in the next update.

**Comment by DarkKronicle** [comment]
Updated
