### ISSUE TITLE
[BUG] Incompatibility with Colorful Subtitles

### ISSUE THREAD

**Issue by egeesin** [DarkKronicle/BetterBlockOutline#2]
Doesn't launch with Colorful Subtitles mod.

**Minecraft Info**
Minecraft 1.18.1
- BetterBlockOutline 1.4.1-1.18.1
- Colorful Subtitles v1.0.0
- Fabric API 0.46.2+1.18

**To Reproduce**
1. Launch the game.
2. Crashes.

**Expected behavior**
To be able to launch the game with all mentioned mods together successfully.

**Additional context**
[latest.log](https://paste.ee/p/82g4I)

**Comment by vacla** [comment]
@egeesin you dont have malilib installed

**Comment by egeesin** [comment]
Oh right, I haven't seen any missing dependency in Fabric client so I assumed that was something else. I'm going to check this again...

**Comment by egeesin** [comment]
Alright, I confirmed that the incompatibility issue is not caused by BetterBlockOutline or any other mod I mentioned here. I'm closing this. If it's possible, please delete this issue. Because there isn't any relevancy to this mod and will not add any value to as previous record/referance.
