### ISSUE TITLE
[FEATURE] Potential support for 2-tall blocks from other mods? 

### ISSUE THREAD

**Issue by coornio** [DarkKronicle/BetterBlockOutline#4]
The title explains the question fairly well. Some mods may introduce blocks that are more than one block high, such as the Waystones mod:

![image](https://user-images.githubusercontent.com/11655762/155147109-8b1551a2-09cf-4fec-8992-afe7d9f5b991.png)

Any chance the Seamless option for the block outline might encompass the top half of the steele as well? 

Also, the writing on the steele overlaps the outlines, not sure if normal. Although, if the outline is corrected to properly encompass the whole block, the overlap won't matter.

**Comment by cabbagegod** [comment]
2 tall blocks are already supported, like tall grass in Vanilla works just fine it would seem. The reason this mod doesn't work is because the block is actually (technically) two blocks. There isn't any (clean) way this mod could fix that, it really falls on the original mod developer.

**Comment by coornio** [comment]
I was not entirely certain where the issue in this scenario lay, so I thank you for the reply. Since this is something that'd need to be rectified by the Waystones dev, I shall bring this to their attention instead!

**Comment by DarkKronicle** [comment]
Minecraft doesn’t handle two block high blocks that well internally. They are still 2 separate blocks with some weird logic connecting them. To have BBO work with them there had to be custom logic written for each block. For vanilla connected blocks most of the logic is the same, but I don’t think there’s a way to globally do it.

**Comment by cabbagegod** [comment]
I don't think there's a way to do it automatically, only thing I could think of would be allow the user to input block IDs that would connect them together. But that's not a very clean solution, maybe useful if someone was using the mod in a modpack but besides from that it doesn't seem realistic.
