### ISSUE TITLE
Block Outline Can still be seen even after i stop hovering

### ISSUE THREAD

**Issue by JustSmebody** [DarkKronicle/BetterBlockOutline#6]
When i press M with some other key like R or T and Im hovering my crosshair on a block the block outline can still be even after i hover my crosshair away from the block it can still be seen.

**Comment by DarkKronicle** [comment]
That’s a keybind to toggle persistence. It can be disabled in the hotkeys section of the configuration.

**Comment by JustSmebody** [comment]
okay
