### ISSUE TITLE
[BUG] Crash on Quilt Loader

### ISSUE THREAD

**Issue by LostLuma** [DarkKronicle/BetterBlockOutline#8]
**Describe the bug**
Attempting to use the mod on quilt results in the game crashing on startup.

**Minecraft Info**
Minecraft information: Minecraft 1.19 with Quilt Loader 0.17.0

**To Reproduce**
1. Put mod in mods folder
2. Attempt to start the game

**Expected behavior**
The game launches.

**Screenshots**
https://files.lostluma.dev/ALHpx3.txt

**Additional context**
Add any other context about the problem here. This could be a mods list, server, etc.

**Comment by vacla** [comment]
@LostLuma you need to install darkkore also

**Comment by LostLuma** [comment]
I must've missed that on the modrinth page earlier, sorry for the confusion.

Maybe the library should just be bundled though since this option is rather inconvenient as an end user.
