### ISSUE TITLE
[BUG] Crash on Config Tabs

### ISSUE THREAD

**Issue by KateReller** [DarkKronicle/BetterBlockOutline#9]
**Describe the bug**
Game crashes when I click any menu category in the mod's settings page.

**Minecraft Info**
Crash info Not Enough Crashes gave me:
https://crashy.net/HG8naHMjiVJCbyFyzpCn

Raw text of the crash:
https://bytebin.lucko.me/HfiNuj2T3o

**To Reproduce**
1. Open mod options.
2. Click on any category, like 'Color Modifiers'.
3. See error

**Comment by TheKodeToad** [comment]
I have this issue too.

**Comment by DarkKronicle** [comment]
Oop yeah I'll get this fixed

**Comment by DarkKronicle** [comment]
Fixed

**Comment by KateReller** [comment]
Issue has reappeared: https://mclo.gs/gUTTlWV
